stickpressed_horizontal = false
stickpressed_vertical = false
scr_initinput()
alpha = 0
spr_character = spr_player_panic
spr_palette = spr_peppalette
char_string = "pep"
bigtext = "Peppino Spaghetti"
smalltext = "A PORTLY ITALIAN CHEF TRYING TO KEEP HIS SHOP IN BUSINESS"
character_selected = 0
bg_x = 0
bg_y = 0
char_index = 0
ready = false
donecharswitch = false
snd_selected = "event:/sfx/misc/collectpizza"
fadeout = false
spr_selected = spr_player_hurt
xoffset = 0
yoffset = 0
taunt = false
spr_taunt = spr_player_taunt
snd_taunt = "event:/sfx/pep/taunt"
taunt_index = 0
eff_index = 0
draw_taunt = false
menu_select = 0
off1 = 0
off2 = 25
off3 = 25
off4 = 25
paletteselect = obj_player.paletteselect
clothesoffset = 500
